# Healthcare Service Log Portal - Production Configuration
# Use this file for production-specific overrides

version: '3.8'

services:
  healthcare-portal:
    restart: always
    mem_limit: 2g
    cpus: 1.5
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - ENABLE_METRICS=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health/basic"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  healthcare-backup:
    restart: always
    mem_limit: 512m
    cpus: 0.5

  nginx:
    restart: always
    mem_limit: 256m
    cpus: 0.5
    depends_on:
      - healthcare-portal

  healthcare-monitor:
    restart: always
    mem_limit: 1g
    cpus: 0.5