# Healthcare Service Log Portal - Development Override
# Use this file for development-specific configurations

version: '3.8'

services:
  healthcare-portal:
    build:
      target: development
    volumes:
      - ./backend/src:/app/src
      - ./frontend/src:/app/frontend/src
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - ENABLE_METRICS=true
      - RATE_LIMIT_MAX=10000
    ports:
      - "3001:3001"
      - "9229:9229"  # Node.js debugging port
    command: ["npm", "run", "dev"]

  # Remove production services in development
  healthcare-backup:
    profiles:
      - production

  nginx:
    profiles:
      - production
      
  healthcare-monitor:
    profiles:
      - production